
vocation_been_used: paladin
hp_pct_to_use_light_heal: 97

# tava 85 subi pra 90
hp_pct_to_use_big_heal: 95



# qndo for hunt assada
#hp_pct_to_pot_life: 85
hp_pct_to_pot_life: 70

# pra hunt assada pode deixar em 70
mana_pct_to_use_pot: 60

auto_attack: true

food_to_eat: "0"
utura_gran: "9"
haste: "F10"

hp_pct_to_use_ssa: 55
hp_pct_to_use_might_ring: 55

# qndo for hunt assada: # pra sanguine eh 95!
# hp_pct_to_use_ssa: 75
# hp_pct_to_use_might_ring: 75